on: [push]

jobs:
  package:
    strategy:
      matrix:
        format:
          - deb
          - rpm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: kentik/pkg@v1.0.0-rc8
      with:
        name: dasharo-acpi-dkms
        version: 0.9.0
        arch: x86_64
        format: ${{ matrix.format }}
        package: packaging/package.yaml

    - uses: actions/upload-artifact@v4
      with:
        path: "*.${{ matrix.format }}"
        name: dasharo-acpi-dkms.${{ matrix.format }}
